const state={debts:[],creditors:[],query:'',updatedAt:''};
const eur=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'});const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const amount=d=>Number(d?.betrag??d?.amount??0)||0;const nameOf=d=>String(d?.name||d?.glaeubiger||d?.creditor||'Ohne Name').trim()||'Ohne Name';const categoryOf=d=>String(d?.category||d?.kategorie||d?.gruppe||'–').trim()||'–';const caseOf=d=>String(d?.aktenzeichen||d?.caseNumber||d?.referenceNumber||d?.kundennummer||d?.customerNumber||'–').trim()||'–';const reasonOf=d=>String(d?.grund||d?.reason||'–').trim()||'–';const isClosed=v=>/bezahlt|erledigt|geschlossen|paid|done|settled|abgeschlossen/i.test(String(v||''));const statusOf=d=>isClosed(d?.status)?'Erledigt':String(d?.status||'Offen');
function paperlessId(link){if(link==null)return'';if(typeof link==='number'||/^\d+$/.test(String(link)))return String(link);if(typeof link!=='object')return'';const direct=link.id??link.documentId??link.paperlessId??link.paperless_id??link.document_id;if(direct!=null&&/^\d+$/.test(String(direct)))return String(direct);const u=String(link.url||link.href||link.downloadUrl||'');const m=u.match(/documents\/(\d+)/i)||u.match(/\/(\d+)(?:\/|$)/);return m?m[1]:''}
function docsOf(d){const p=Array.isArray(d?.paperlessLinks)?d.paperlessLinks.map(x=>({...x,__source:'Paperless',__id:paperlessId(x)})):[];const c=Array.isArray(d?.correspondence)?d.correspondence.map(x=>({...x,__source:'Datei'})):[];return[...p,...c]}
function groupCreditors(debts){const map=new Map();debts.forEach((d,i)=>{const n=nameOf(d),k=n.toLocaleLowerCase('de-DE');if(!map.has(k))map.set(k,{name:n,total:0,open:0,count:0,closedCount:0,categories:new Set(),debts:[],docs:[]});const g=map.get(k);g.total+=amount(d);if(!isClosed(d?.status))g.open+=amount(d);else g.closedCount++;g.count++;if(categoryOf(d)!=='–')g.categories.add(categoryOf(d));g.debts.push({...d,__index:i});g.docs.push(...docsOf(d).map(x=>({...x,__debtIndex:i,__creditor:n}))) });return[...map.values()].sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name,'de'))}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function showLogin(){document.getElementById('loginView').classList.remove('hidden');document.getElementById('appView').classList.add('hidden')}
function showApp(){document.getElementById('loginView').classList.add('hidden');document.getElementById('appView').classList.remove('hidden')}
function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+page));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'});if(page==='documents')renderDocuments()}
function tableFor(list,limit){const rows=(limit?list.slice(0,limit):list).map(g=>`<tr><td><strong>${esc(g.name)}</strong><div class="mini">${g.count} Eintrag${g.count===1?'':'e'}</div></td><td class="amount">${eur.format(g.total)}</td><td><span class="badge ${g.open>0?'open':'closed'}">${g.open>0?'Offen':'Erledigt'}</span></td><td>${esc([...g.categories][0]||'–')}</td><td><button class="iconBtn" data-open-creditor="${state.creditors.indexOf(g)}">›</button></td></tr>`).join('');return`<div class="tableWrap"><table><thead><tr><th>Gläubiger</th><th>Betrag</th><th>Status</th><th>Kategorie</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="5"><div class="empty">Keine Gläubiger gefunden.</div></td></tr>'}</tbody></table></div>`}
function creditorCards(list){return`<div class="creditorGrid">${list.map(g=>{const idx=state.creditors.indexOf(g);return`<article class="creditorCard glass"><span class="badge ${g.open>0?'open':'closed'}">${g.open>0?'Offen':'Erledigt'}</span><h3>${esc(g.name)}</h3><div class="total">${eur.format(g.total)}</div><div class="mini">${g.count} Eintrag${g.count===1?'':'e'} · ${esc([...g.categories][0]||'–')}</div><div class="cardActions"><button class="btn" data-open-creditor="${idx}">Details öffnen</button></div></article>`}).join('')||'<div class="empty">Keine Gläubiger gefunden.</div>'}</div>`}
function notesText(d){const arr=Array.isArray(d?.notesHistory)?d.notesHistory:[];if(arr.length)return arr.slice(-5).reverse().map(n=>esc(n.text||'')).filter(Boolean).join('<br>');return d?.notes?esc(d.notes):''}
function historyText(d){const arr=Array.isArray(d?.history)?d.history:[];if(!arr.length)return'';return arr.slice(-5).reverse().map(h=>esc(h.text||h.action||h.type||'Änderung')).join('<br>')}
function openCreditor(idx){const g=state.creditors[idx];if(!g)return;const entries=g.debts.map(d=>{const c=d.contactDetails||{};const docs=docsOf(d).map(doc=>{if(doc.__source==='Paperless'&&doc.__id)return`<a target="_blank" rel="noopener" href="/api/advisor/paperless/document/${doc.__id}">${esc(doc.title||doc.name||('Paperless #'+doc.__id))}</a>`;return`<span>${esc(doc.title||doc.name||'Datei')}</span>`}).join('');const notes=notesText(d),hist=historyText(d);return`<div class="debtEntry"><h4>${esc(reasonOf(d))}</h4><p><b>Betrag:</b> ${eur.format(amount(d))} · <b>Status:</b> ${esc(statusOf(d))}</p><p><b>Aktenzeichen:</b> ${esc(caseOf(d))} · <b>Kategorie:</b> ${esc(categoryOf(d))}</p>${c.representative||c.email||c.phone?`<p><b>Ansprechpartner:</b> ${esc(c.representative||'–')} · ${esc(c.email||c.phone||'')}</p>`:''}${docs?`<div class="docLinks">${docs}</div>`:''}${notes?`<div class="notes"><b>Notizen</b><br>${notes}</div>`:''}${hist?`<div class="notes"><b>Verlauf</b><br>${hist}</div>`:''}</div>`}).join('');$('drawerContent').innerHTML=`<div class="drawerHead"><div><h2>${esc(g.name)}</h2><p>${g.count} Eintrag${g.count===1?'':'e'} · ${g.docs.length} Dokument${g.docs.length===1?'':'e'}</p></div><button class="closeBtn" id="drawerClose">×</button></div><div class="drawerHero glass"><span class="badge ${g.open>0?'open':'closed'}">${g.open>0?'Offen':'Erledigt'}</span><div class="big">${eur.format(g.total)}</div><div class="drawerFacts"><div class="drawerFact"><span>Offen</span><strong>${eur.format(g.open)}</strong></div><div class="drawerFact"><span>Kategorie</span><strong>${esc([...g.categories].join(', ')||'–')}</strong></div><div class="drawerFact"><span>Dokumente</span><strong>${g.docs.length}</strong></div><div class="drawerFact"><span>Einträge</span><strong>${g.count}</strong></div></div></div>${entries}`;$('drawerBack').classList.add('show');$('drawer').classList.add('show');$('drawerClose').onclick=closeDrawer}
function closeDrawer(){$('drawerBack').classList.remove('show');$('drawer').classList.remove('show')}
function renderOverview(){const total=state.debts.reduce((s,d)=>s+amount(d),0),open=state.debts.filter(d=>!isClosed(d?.status)).reduce((s,d)=>s+amount(d),0),closed=state.debts.filter(d=>isClosed(d?.status)).length;$('statTotal').textContent=eur.format(total);$('statOpen').textContent=eur.format(open);$('statCreditors').textContent=state.creditors.length;$('statClosed').textContent=closed;$('updatedAt').textContent=state.updatedAt?('Stand '+new Date(state.updatedAt).toLocaleString('de-DE')):'';$('overviewTable').innerHTML=tableFor(state.creditors,8)}
function renderCreditors(){const q=state.query.trim().toLocaleLowerCase('de-DE');let list=state.creditors;if(q)list=list.filter(g=>[g.name,...g.categories,...g.debts.flatMap(d=>[caseOf(d),reasonOf(d)])].join(' ').toLocaleLowerCase('de-DE').includes(q));$('creditorContent').innerHTML=window.innerWidth<=820?creditorCards(list):tableFor(list)}
function renderDocuments(){const docs=state.creditors.flatMap(g=>g.docs),p=docs.filter(x=>x.__source==='Paperless').length,f=docs.filter(x=>x.__source==='Datei').length,missing=state.creditors.filter(g=>!g.docs.length).length;$('docTotal').textContent=docs.length;$('docPaperless').textContent=p;$('docFiles').textContent=f;$('docMissing').textContent=missing;const html=docs.map(d=>{const title=esc(d.title||d.name||d.driveName||('Dokument '+(d.__id?('#'+d.__id):''))),meta=esc(d.__creditor+' · '+(d.meta||d.date||d.created||'ohne Datum'));if(d.__source==='Paperless'&&d.__id)return`<a class="docCard glass" target="_blank" rel="noopener" href="/api/advisor/paperless/document/${d.__id}" style="color:inherit;text-decoration:none"><div class="docIcon">P</div><div><strong>${title}</strong><span>${meta}</span></div><div class="sourcePill">Öffnen</div></a>`;return`<div class="docCard glass"><div class="docIcon">⌘</div><div><strong>${title}</strong><span>${meta}</span></div><div class="sourcePill">Datei</div></div>`}).join('');$('documentsContent').innerHTML=html?`<div class="docGrid">${html}</div>`:'<div class="empty">Noch keine verknüpften Dokumente.</div>'}
function renderAll(){state.creditors=groupCreditors(state.debts);renderOverview();renderCreditors();renderDocuments()}
async function loadData(){const r=await fetch('/api/advisor/data',{cache:'no-store'});if(r.status===401){showLogin();return false}const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Daten konnten nicht geladen werden');state.debts=Array.isArray(d.debts)?d.debts:[];state.updatedAt=d.updatedAt||'';renderAll();showApp();return true}
async function checkSession(){try{const r=await fetch('/api/advisor/session',{cache:'no-store'}),d=await r.json();if(d.ok)return loadData()}catch(e){}showLogin()}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const m=$('loginMsg');m.textContent='Anmeldung wird geprüft…';try{const r=await fetch('/api/advisor/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('loginUser').value,password:$('loginPass').value})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Anmeldung fehlgeschlagen');m.textContent='';await loadData()}catch(err){m.textContent=err.message}});
$('logoutBtn').onclick=async()=>{await fetch('/api/advisor/logout',{method:'POST'}).catch(()=>{});location.replace('/berater')};
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){showPage(p.dataset.page);return}const o=e.target.closest('[data-open-creditor]');if(o){openCreditor(Number(o.dataset.openCreditor));return}});$('drawerBack').onclick=closeDrawer;$('creditorSearch').addEventListener('input',e=>{state.query=e.target.value;renderCreditors()});window.addEventListener('resize',renderCreditors);checkSession();
