(function(){
'use strict';
const SHEET_NAME='ChatGPT Schulden Import';
const IMPORT_KEY='schulden_chatgpt_import_done_v1';
const DRIVE_SCOPE='https://www.googleapis.com/auth/drive.readonly';
let token='',tokenClient=null,rows=[];
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(msg){try{if(typeof showToast==='function')return showToast(msg);}catch(e){}alert(msg);}
function debtsArr(){try{if(typeof debts!=='undefined'&&Array.isArray(debts))return debts;}catch(e){}try{return Array.isArray(window.debts)?window.debts:[];}catch(e){return [];}}
function doneIds(){try{return new Set(JSON.parse(localStorage.getItem(IMPORT_KEY)||'[]'));}catch(e){return new Set();}}
function saveDone(set){localStorage.setItem(IMPORT_KEY,JSON.stringify([...set]));}
function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();}
function parseMoney(v){let s=String(v??'').trim().replace(/[^0-9,.-]/g,'');if(!s)return 0;const c=s.lastIndexOf(','),d=s.lastIndexOf('.');if(c>=0&&d>=0){if(c>d)s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'');}else if(c>=0)s=s.replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0;}
function normDate(v){const s=String(v??'').trim();if(!s)return'';if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:s;}
function waitGIS(){return new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if(window.google?.accounts?.oauth2){clearInterval(t);resolve();}else if(++n>50){clearInterval(t);reject(new Error('Google-Anmeldung nicht geladen'));}},100);});}
async function clientId(){try{const r=await fetch('/api/config',{cache:'no-store'}),j=await r.json();return j.googleClientId||localStorage.getItem('schulden_google_client_id_v26')||'';}catch(e){return localStorage.getItem('schulden_google_client_id_v26')||'';}}
async function ensureToken(){if(token)return token;const cid=await clientId();if(!cid)throw new Error('Keine Google Client ID eingetragen');await waitGIS();return await new Promise((resolve,reject)=>{tokenClient=google.accounts.oauth2.initTokenClient({client_id:cid,scope:DRIVE_SCOPE,callback:r=>{if(r?.access_token){token=r.access_token;resolve(token);}else reject(new Error(r?.error||'Google-Freigabe fehlgeschlagen'));}});tokenClient.requestAccessToken({prompt:'consent'});});}
async function driveJson(url){const t=await ensureToken(),r=await fetch(url,{headers:{Authorization:'Bearer '+t},cache:'no-store'});if(!r.ok)throw new Error('Google Drive Fehler '+r.status);return r.json();}
async function driveText(url){const t=await ensureToken(),r=await fetch(url,{headers:{Authorization:'Bearer '+t},cache:'no-store'});if(!r.ok)throw new Error('Google Drive Export Fehler '+r.status);return r.text();}
function csvParse(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(q){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')q=false;else cell+=ch;}else{if(ch==='"')q=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));out.push(row);row=[];cell='';}else cell+=ch;}}if(cell||row.length){row.push(cell);out.push(row);}return out;}
async function loadRows(){const q=encodeURIComponent(`name='${SHEET_NAME.replace(/'/g,"\\'")}' and mimeType='application/vnd.google-apps.spreadsheet' and trashed=false`),found=await driveJson('https://www.googleapis.com/drive/v3/files?q='+q+'&fields=files(id,name,modifiedTime)&pageSize=10'),file=(found.files||[])[0];if(!file)throw new Error('Import-Tabelle nicht gefunden');const csv=await driveText('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(file.id)+'/export?mimeType=text%2Fcsv'),data=csvParse(csv);if(data.length<2)return[];const h=data[0].map(x=>String(x).trim());return data.slice(1).filter(r=>r.some(x=>String(x).trim())).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])));}
function importId(r,i){return String(r['Import-ID']||`row-${i+2}-${r['Gläubiger']||''}-${r['Aktenzeichen']||''}`);}
function col(r,...names){for(const n of names){if(r[n]!==undefined&&String(r[n]).trim()!=='')return r[n];}return'';}
function mapRow(r,i){const id=importId(r,i),statusRaw=String(col(r,'Status')||'').trim(),noteBits=[];if(col(r,'Notiz'))noteBits.push(col(r,'Notiz'));if(statusRaw&&!/^offen$/i.test(statusRaw))noteBits.push('Import-Status: '+statusRaw);if(col(r,'Quelle'))noteBits.push('Quelle: '+col(r,'Quelle'));const pl=String(col(r,'Paperless-Dokument-ID','Paperless ID')||'').trim(),address=String(col(r,'Anschrift','Adresse')||'').trim(),representative=String(col(r,'Ansprechpartner','Vertreter')||'').trim(),email=String(col(r,'E-Mail','Email')||'').trim(),phone=String(col(r,'Telefon')||'').trim(),category=String(col(r,'Kategorie')||'Sonstiges').trim()||'Sonstiges';const debt={name:String(col(r,'Gläubiger','Glaeubiger')||'').trim(),grund:String(col(r,'Grund')||'Forderung').trim()||'Forderung',reason:String(col(r,'Grund')||'Forderung').trim()||'Forderung',betrag:parseMoney(col(r,'Betrag')),amount:parseMoney(col(r,'Betrag')),datum:normDate(col(r,'Frist','Datum')),date:normDate(col(r,'Frist','Datum')),aktenzeichen:String(col(r,'Aktenzeichen')||'').trim(),caseNumber:String(col(r,'Aktenzeichen')||'').trim(),kundennummer:String(col(r,'Kundennummer')||'').trim(),customerNumber:String(col(r,'Kundennummer')||'').trim(),category,kategorie:category,status:'offen',contactDetails:{representative,address,email,phone},contactPerson:[representative,address,email,phone].filter(Boolean).join(' | '),notes:'',notesHistory:noteBits.length?[{at:new Date().toISOString(),text:noteBits.join(' · ')}]:[],payments:[],correspondence:[],paperlessLinks:pl?[{id:pl,title:'Paperless Dokument #'+pl,meta:'Aus ChatGPT Import',linkedAt:new Date().toISOString()}]:[],chatgptImportId:id,chatgptImportSource:String(col(r,'Quelle')||'').trim(),editHistory:[{at:new Date().toISOString(),text:'Über ChatGPT-Import angelegt'}]};return{id,debt,row:r};}
function duplicateAnalysis(d){const hits=[];for(const [i,x] of debtsArr().entries()){const why=[];if(norm(x.name)&&norm(x.name)===norm(d.name))why.push('gleicher Gläubiger');const a=norm(x.aktenzeichen||x.caseNumber||''),b=norm(d.aktenzeichen||d.caseNumber||'');if(a&&b&&a===b)why.push('gleiches Aktenzeichen');if(Number(x.betrag)>0&&Math.abs(Number(x.betrag)-Number(d.betrag))<0.01)why.push('gleicher Betrag');const xid=new Set((Array.isArray(x.paperlessLinks)?x.paperlessLinks:[]).map(p=>String(p.id))),did=(Array.isArray(d.paperlessLinks)?d.paperlessLinks:[]).map(p=>String(p.id));if(did.some(id=>xid.has(id)))why.push('gleiches Paperless-Dokument');if(why.includes('gleiches Aktenzeichen')||why.includes('gleiches Paperless-Dokument')||why.length>=2)hits.push({i,why,name:x.name});}return hits;}
function ensureUI(){if($('chatgptImportBtn'))return;const st=document.createElement('style');st.id='chatgptImportStyleV131';st.textContent=`#chatgptImportBtn{position:fixed;right:18px;bottom:18px;z-index:9500;min-height:46px;border-radius:16px;padding:0 16px;font-weight:900;box-shadow:0 14px 34px rgba(0,0,0,.25)}.cgiOverlay{position:fixed;inset:0;z-index:17000;background:rgba(2,6,18,.78);backdrop-filter:blur(12px);display:flex;align-items:center;justify-content:center;padding:18px}.cgiModal{width:min(980px,96vw);max-height:92vh;overflow:auto;background:#111a2b;color:#eaf2ff;border:1px solid rgba(255,255,255,.12);border-radius:26px;padding:20px}.cgiHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.cgiHead h3{margin:0}.cgiHead p{margin:5px 0 0;color:#9fb0cc}.cgiClose{min-width:42px;width:42px;height:42px;padding:0;border-radius:14px}.cgiToolbar,.cgiActions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.cgiList{display:grid;gap:10px}.cgiItem{padding:14px;border-radius:18px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08)}.cgiTop{display:flex;justify-content:space-between;gap:12px}.cgiItem strong{font-size:16px}.cgiMeta{margin-top:7px;color:#aebed8;font-size:13px;line-height:1.5}.cgiActions{margin-top:10px}.cgiActions button{min-height:36px;border-radius:11px;padding:0 11px;font-size:12px}.cgiSkip{opacity:.52}.cgiEmpty{padding:18px;text-align:center;color:#aebed8;background:rgba(255,255,255,.04);border-radius:16px}.cgiWarn{margin-top:8px;padding:8px 10px;border-radius:10px;background:rgba(245,158,11,.12);color:#ffd98a}.cgiEdit{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:12px;padding:12px;border-radius:14px;background:rgba(0,0,0,.18)}.cgiEdit label{font-size:11px;color:#9fb0cc}.cgiEdit input{width:100%;min-height:38px;margin-top:4px;border-radius:10px;padding:0 9px;background:#16243a;color:#fff}.cgiEdit .wide{grid-column:1/-1}@media(max-width:620px){.cgiEdit{grid-template-columns:1fr}}`;document.head.appendChild(st);const b=document.createElement('button');b.id='chatgptImportBtn';b.type='button';b.textContent='🤖 ChatGPT Import';b.addEventListener('click',open);document.body.appendChild(b);}
function close(){$('cgiOverlay')?.remove();document.body.classList.remove('modalOpen');}
function editorHtml(x,i){const d=x.debt;return `<div class="cgiEdit" data-cgi-editor="${i}"><label>Gläubiger<input data-f="Gläubiger" value="${esc(d.name)}"></label><label>Betrag<input data-f="Betrag" value="${esc(String(d.betrag).replace('.',','))}"></label><label>Aktenzeichen<input data-f="Aktenzeichen" value="${esc(d.aktenzeichen)}"></label><label>Kundennummer<input data-f="Kundennummer" value="${esc(d.kundennummer)}"></label><label>Frist<input type="date" data-f="Frist" value="${esc(d.datum)}"></label><label>Kategorie<input data-f="Kategorie" value="${esc(d.category)}"></label><label class="wide">Grund<input data-f="Grund" value="${esc(d.grund)}"></label><label class="wide">Anschrift<input data-f="Anschrift" value="${esc(d.contactDetails.address)}"></label><div class="wide cgiActions"><button type="button" data-cgi-edit-save="${i}">Änderungen speichern</button><button type="button" class="secondary" data-cgi-edit-cancel="${i}">Abbrechen</button></div></div>`;}
function render(editIndex=-1){const box=$('cgiList');if(!box)return;const done=doneIds(),mapped=rows.map(mapRow);if(!mapped.length){box.innerHTML='<div class="cgiEmpty">Keine Import-Einträge vorhanden.</div>';return;}box.innerHTML=mapped.map((x,i)=>{const finished=done.has(x.id)||debtsArr().some(d=>d.chatgptImportId===x.id),dup=duplicateAnalysis(x.debt),editing=i===editIndex;return `<div class="cgiItem ${finished?'cgiSkip':''}"><div class="cgiTop"><strong>${esc(x.debt.name||'Ohne Gläubiger')}</strong><b>${Number(x.debt.betrag||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'})}</b></div><div class="cgiMeta">Aktenzeichen: ${esc(x.debt.aktenzeichen||'–')} · Kundennummer: ${esc(x.debt.kundennummer||'–')} · Frist: ${esc(x.debt.datum||'–')} · Kategorie: ${esc(x.debt.category||'–')}${finished?'<br>✓ Bereits bearbeitet':''}</div>${dup.length?`<div class="cgiWarn">⚠️ Mögliche Dublette: ${dup.map(h=>esc((h.name||'Eintrag')+' ('+h.why.join(', ')+')')).join(' · ')}</div>`:''}${editing?editorHtml(x,i):''}<div class="cgiActions">${finished?'':`<button type="button" data-cgi-add="${i}">Übernehmen</button><button type="button" class="secondary" data-cgi-edit="${i}">Bearbeiten</button><button type="button" class="secondary" data-cgi-ignore="${i}">Ablehnen</button>`}</div></div>`;}).join('');}
function applyEditor(i){const ed=document.querySelector(`[data-cgi-editor="${i}"]`);if(!ed)return;const r=rows[i];for(const inp of ed.querySelectorAll('[data-f]'))r[inp.dataset.f]=inp.value;render();toast('Import-Vorschau aktualisiert.');}
function addIndex(i){const x=mapRow(rows[i],i);if(!x.debt.name){toast('Gläubigername fehlt');return;}if(!(x.debt.betrag>0)){toast('Betrag fehlt oder ist 0');return;}const dup=duplicateAnalysis(x.debt);if(dup.length&&!confirm('Es gibt einen Dubletten-Hinweis. Eintrag trotzdem übernehmen?'))return;debtsArr().push(x.debt);const d=doneIds();d.add(x.id);saveDone(d);try{if(typeof window.save==='function')window.save();else if(typeof save==='function')save();}catch(e){}try{if(typeof window.render==='function')window.render();else if(typeof render==='function')render();}catch(e){}render();toast('Gläubiger übernommen ✅');}
function ignoreIndex(i){const x=mapRow(rows[i],i),d=doneIds();d.add(x.id);saveDone(d);render();}
async function open(){ensureUI();let o=$('cgiOverlay');if(!o){o=document.createElement('div');o.id='cgiOverlay';o.className='cgiOverlay';o.innerHTML='<div class="cgiModal"><div class="cgiHead"><div><h3>🤖 ChatGPT Import</h3><p>Import-Vorschau: prüfen, bearbeiten oder ablehnen. Nichts wird ohne Bestätigung übernommen.</p></div><button class="cgiClose" type="button" data-cgi-close>×</button></div><div class="cgiToolbar"><button type="button" data-cgi-refresh>Neu laden</button><button type="button" class="secondary" data-cgi-reset>Abgelehnte wieder anzeigen</button></div><div id="cgiList" class="cgiList"><div class="cgiEmpty">Lade Import-Tabelle…</div></div></div>';document.body.appendChild(o);document.body.classList.add('modalOpen');o.addEventListener('click',e=>{if(e.target===o||e.target.closest('[data-cgi-close]')){close();return;}const a=e.target.closest('[data-cgi-add]');if(a){addIndex(Number(a.dataset.cgiAdd));return;}const ig=e.target.closest('[data-cgi-ignore]');if(ig){ignoreIndex(Number(ig.dataset.cgiIgnore));return;}const ed=e.target.closest('[data-cgi-edit]');if(ed){render(Number(ed.dataset.cgiEdit));return;}const sv=e.target.closest('[data-cgi-edit-save]');if(sv){applyEditor(Number(sv.dataset.cgiEditSave));return;}if(e.target.closest('[data-cgi-edit-cancel]')){render();return;}if(e.target.closest('[data-cgi-refresh]')){refresh();return;}if(e.target.closest('[data-cgi-reset]')){localStorage.removeItem(IMPORT_KEY);render();return;}});}await refresh();}
async function refresh(){const box=$('cgiList');if(box)box.innerHTML='<div class="cgiEmpty">Google Drive wird gelesen…</div>';try{rows=await loadRows();render();}catch(e){if(box)box.innerHTML='<div class="cgiEmpty">Import konnte nicht geladen werden: '+esc(e.message||e)+'</div>';}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureUI,{once:true});else ensureUI();
})();